# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 363e5edfa6bbfc78fabc2f9c66174482bb5270fafd00a08a2e3ff7e167783f7b5b60a77e7daac587251604286fcd82f5a9fa48bfab77b81b05d85a1a696e7103

test:
  secret_key_base: 528c548b94e95c3759c36757812271bcd85cb2fc7d328f38cb0e0c4dc01d281b06d0011a1d02679d8ac47a24260a88570da3d18a507c9e63c7d3e0c79570f7dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
